"""
Async wrapper for the 3x-ui (X-UI) panel REST API.
Uses Bearer token authentication via httpx.
"""

from __future__ import annotations

import logging
from typing import Any

import httpx

from config import XUI_BASE_URL, XUI_API_TOKEN

logger = logging.getLogger(__name__)

_client: httpx.AsyncClient | None = None


def _get_client() -> httpx.AsyncClient:
    global _client
    if _client is None or _client.is_closed:
        _client = httpx.AsyncClient(
            base_url=XUI_BASE_URL,
            headers={
                "Authorization": f"Bearer {XUI_API_TOKEN}",
                "Content-Type": "application/json",
            },
            verify=False,  # Self-signed certs common on panels
            timeout=30.0,
        )
    return _client


async def _request(
    method: str,
    path: str,
    json_data: dict | None = None,
    params: dict | None = None,
) -> dict[str, Any]:
    """Make an authenticated request to X-UI and return the parsed JSON."""
    client = _get_client()
    resp = await client.request(method, path, json=json_data, params=params)
    resp.raise_for_status()
    data = resp.json()
    if not data.get("success", False):
        msg = data.get("msg", "Unknown X-UI error")
        logger.error("X-UI API error: %s (path=%s)", msg, path)
        raise RuntimeError(f"X-UI API error: {msg}")
    return data


# ──────────────────────────── Inbounds ────────────────────────────


async def list_inbounds() -> list[dict[str, Any]]:
    data = await _request("GET", "/panel/api/inbounds/list")
    return data.get("obj", [])


async def get_inbound(inbound_id: int) -> dict[str, Any]:
    data = await _request("GET", f"/panel/api/inbounds/get/{inbound_id}")
    return data.get("obj", {})


# ──────────────────────────── Clients ────────────────────────────


async def add_client(
    email: str,
    total_gb: int,
    expiry_time: int,
    tg_id: int,
    inbound_ids: list[int],
    enable: bool = True,
    limit_ip: int = 0,
) -> dict[str, Any]:
    """
    Create a new client and attach it to the given inbounds.

    Args:
        email: Unique client email identifier.
        total_gb: Total traffic limit in bytes (NOT GB — pass gb * 1073741824).
        expiry_time: Expiration as Unix timestamp in milliseconds.
        tg_id: Telegram user ID.
        inbound_ids: List of inbound IDs to attach the client to.
        enable: Whether the client is enabled.
        limit_ip: IP limit (0 = unlimited).

    Returns:
        The API response data.
    """
    payload = {
        "client": {
            "email": email,
            "totalGB": total_gb,
            "expiryTime": expiry_time,
            "tgId": tg_id,
            "limitIp": limit_ip,
            "enable": enable,
            "subId": "",  # Auto-generated by server
            "reset": 0,
            "comment": "",
            "security": "auto",
        },
        "inboundIds": inbound_ids,
    }
    data = await _request("POST", "/panel/api/clients/add", json_data=payload)
    return data


async def get_client(email: str) -> dict[str, Any] | None:
    """Fetch a single client by email.

    The API returns a nested object: {client: {...}, inboundIds: [...], ...}.
    This function returns the inner 'client' dict for convenience.
    Returns None if not found.
    """
    try:
        data = await _request("GET", f"/panel/api/clients/get/{email}")
        obj = data.get("obj")
        if obj is None:
            return None
        # API may return the wrapper object with 'client' key
        if isinstance(obj, dict) and "client" in obj:
            return obj["client"]
        return obj
    except (RuntimeError, httpx.HTTPStatusError):
        return None


async def get_client_full(email: str) -> dict[str, Any] | None:
    """Fetch a single client by email — returns the FULL wrapper object
    including client, inboundIds, externalLinks, usedTraffic.
    """
    try:
        data = await _request("GET", f"/panel/api/clients/get/{email}")
        return data.get("obj")
    except (RuntimeError, httpx.HTTPStatusError):
        return None


async def get_clients_by_tg_id(tg_id: int) -> list[dict[str, Any]]:
    """Fetch all clients associated with a Telegram user ID.

    Returns a list of wrapper objects, each containing:
      - client: dict with email, subId, uuid, totalGB, expiryTime, tgId, ...
      - inboundIds: list[int]
      - usedTraffic: int (bytes)
      - externalLinks: list
    """
    try:
        data = await _request("GET", f"/panel/api/clients/get/tgId/{tg_id}")
        obj = data.get("obj")
        if isinstance(obj, list):
            return obj
        if obj is not None:
            return [obj]
        return []
    except (RuntimeError, httpx.HTTPStatusError):
        return []


async def update_client(
    email: str,
    client_data: dict[str, Any],
) -> dict[str, Any]:
    """
    Update a client by email. Sends a flat JSON body with client fields.

    The X-UI Go backend expects:
      - A flat JSON object with client fields (email, totalGB, etc.)
      - The 'id' field to be a string (the client's UUID), not the integer DB row ID.
    """
    payload = dict(client_data)

    # The Go backend expects 'id' as a string (UUID), but the GET response
    # returns 'id' as an integer (DB row ID). Replace it with the uuid field.
    if "uuid" in payload:
        payload["id"] = payload["uuid"]
    elif isinstance(payload.get("id"), int):
        payload.pop("id", None)

    # Ensure email is present (required by the API)
    if "email" not in payload:
        payload["email"] = email

    data = await _request(
        "POST", f"/panel/api/clients/update/{email}", json_data=payload
    )
    return data


async def delete_client(email: str) -> dict[str, Any]:
    """Delete a client by email."""
    data = await _request("POST", f"/panel/api/clients/del/{email}")
    return data


async def get_client_traffic(email: str) -> dict[str, Any] | None:
    """Get traffic stats for a client."""
    try:
        data = await _request("GET", f"/panel/api/clients/traffic/{email}")
        return data.get("obj")
    except (RuntimeError, httpx.HTTPStatusError):
        return None


async def get_sub_links(sub_id: str) -> list[str]:
    """Get subscription links by subscription ID."""
    try:
        data = await _request("GET", f"/panel/api/clients/subLinks/{sub_id}")
        return data.get("obj", [])
    except (RuntimeError, httpx.HTTPStatusError):
        return []


async def get_client_links(email: str) -> list[str]:
    """Get individual config links for a client across all attached inbounds."""
    try:
        data = await _request("GET", f"/panel/api/clients/links/{email}")
        return data.get("obj", [])
    except (RuntimeError, httpx.HTTPStatusError):
        return []


async def close_client() -> None:
    """Close the httpx client on shutdown."""
    global _client
    if _client is not None and not _client.is_closed:
        await _client.aclose()
        _client = None
